<?php
$auth = Zend_Auth::getInstance();
if($auth->hasIdentity()){
	$username = $auth->getIdentity()->email;
	$logoutUrl = $this->url(array(), 'userLogout');  ?>
	<p class="no-margin">
		<span class="bold">Přihlášen: </span> <?php echo $this->escape($username); ?>
	</p>
	<p class="no-margin">
		<a href="<?php echo $logoutUrl;?>">Odhlásit se</a>
	</p>
<?php }
else{
	$loginUrl = $this->url(array(), 'userLogin');
	$registerUrl = $this->url(array(), 'userRegister'); ?>
	<p class="no-margin"><a href="<?php echo $loginUrl?>">Přihlásit se</a></p>
	<p class="no-margin"><a href="<?php echo $registerUrl?>">Registrovat se</a></p>
<?php }