<p><a href="<?php echo $this->url(
		array(),
		'bookNew') ?>">Přidat novou knihu</a></p>

<h2>Knihy:</h2>
<table>
<?php foreach ($this->entries as $entry):?>
<tr>
	<td><?php echo $this->escape($entry->name)?></td>
	<td><?php echo $this->escape($entry->author)?></td>
	<td><a href="<?php echo $this->url(
			array('idBook' => $this->escape($entry->idBook)),
			'bookDetail') ?>">Detail knihy</a></td>
	<td><a href="<?php echo $this->url(
			array('idBook' => $this->escape($entry->idBook)),
			'bookEdit') ?>">Editovat knihu</a></td>
	<td>
		<form action="<?php echo $this->url(
				array('idBook' => $this->escape($entry->idBook)),
				'bookDelete') ?>" method="post">
				<input type="submit" onclick="return confirm('Opravdu chcete knihu smazat?')" value="Smazat knihu"/>
		</form>
	</td>
</tr>
<?php endforeach ?>
</table>