<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<?php echo $this->headMeta (); ?>
	<?php $this->headTitle('Ukázková aplikace - Zend Framework ');
	echo $this->headTitle();?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl('css/global.css'), 'screen, projection'); ?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl('css/screen.css'), 'screen, projection'); ?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl('css/ie.css'), 'screen, projection', 'IE');?>
	<?php $this->headLink()->appendStylesheet($this->baseUrl('css/print.css'), 'print'); ?>
	<?php echo $this->headLink();?>
</head>
<body>
<div class="container">
	<div id="header" class="prepend-top">
		<h1 class="span-24"><?php echo "Internetové knihkupectví"; ?></h1>
	</div>
	<div id="main-content" class="span-24">
		<?php echo $this->messages(); ?>
		<?php echo $this->layout()->content; ?>
	</div>
</div>

</body>
</html>